# Generated by mm.pl: Mon Mar  9 13:58:39 MST 1998


# Wrap make components from SHARED_ROOT and the current directory in the 
# proper order so that variables like ODIR have the correct directory-specific 
# value at the right moment.  See the included files for details of what they 
# are doing. This file should NOT be manually edited.

# Set NEXTDIR, THISDIR and DIR_LIST
include $(SHARED_ROOT)/include1.mk

# Include list of subdirectories to process
-include $(THISDIR)/subdir.mk

# Set ODIR, PROJECT_INCLUDES, UNIQUE
include $(SHARED_ROOT)/include2.mk

# Set list of object files, relative to ODIR
-include $(THISDIR)/objfile.mk

# Set rules for the ODIR directory 
include $(SHARED_ROOT)/compilerules.mk

# Remove current dir from DIR_LIST
DIR_LIST :=$(filter-out $(firstword $(DIR_LIST)), $(DIR_LIST))


# ACL:rcsinfo
#  ----------------------------------------------------------------------
#  $RCSfile: include.mk,v $   $Author: richard $
#  $Revision: 1.3 $   $Date: 2004/11/01 18:17:02 $
#  ----------------------------------------------------------------------
# ACL:rcsinfo
