# Generated by mm.pl: Mon Mar  9 13:58:39 MST 1998

# Set ODIR, PROJECT_INCLUDES, UNIQUE
include $(SHARED_ROOT)/include2.mk

# Object file list.
# This list is user-editable.

$(UNIQUE)_OBJS := \
	$(ODIR)/DynamicLayout.cmpl.o \
	$(ODIR)/GlobalIDDataBase.cmpl.o

LOCAL_OBJS += $($(UNIQUE)_OBJS)

# Set rules for the ODIR directory 
include $(SHARED_ROOT)/compilerules.mk

# ACL:rcsinfo
#  ----------------------------------------------------------------------
#  $RCSfile: objfile.mk,v $   $Author: richi $
#  $Revision: 1.12 $   $Date: 2004/11/02 12:29:44 $
#  ----------------------------------------------------------------------
# ACL:rcsinfo
