/*******************************************************
 * FreePOOMA version information file for suite: LINUXeko
 * Created Wed Oct 25 11:22:29 PDT 2006 by mochi on eng-15
 * Generated by configure --arch LINUXeko --opt
 *******************************************************/

#ifndef POOMA_GENERATED_CONFIG_H
#define POOMA_GENERATED_CONFIG_H

#define POOMA_YES                          1
#define POOMA_NO                           0
#define POOMA_TRUE                         true
#define POOMA_FALSE                        false
#define POOMA_SUITE                        "LINUXeko"
#define POOMA_ARCH_TYPE                    "linux"
#define POOMA_COMP_TYPE                    "pathcc"
#define POOMA_MAJOR_VERSION                2
#define POOMA_MINOR_VERSION                4
#define POOMA_PATCH_LEVEL                  "1"
#define POOMA_VERSION_STRING               "FreePOOMA 2.4.1"
#define POOMA_VERSION_NUM_STRING           "2.4.1"
#define POOMA_CONFIGURE_ARGS               "--arch LINUXeko --opt"
#define POOMA_BUILD_DATE                   "Wed Oct 25 11:22:29 PDT 2006"
#define POOMA_BUILD_USER                   "mochi"
#define POOMA_BUILD_HOST                   "eng-15"
#define POOMA_POOLED                       POOMA_YES
#define POOMA_PRINTDEBUG                   POOMA_NO
#define POOMA_PAWS                         POOMA_NO
#define POOMA_LUX                          POOMA_NO
#define POOMA_HDF5                         POOMA_NO
#define POOMA_FFTW                         POOMA_NO
#define POOMA_PROFILE                      POOMA_NO
#define POOMA_MESSAGING                    POOMA_NO
#define POOMA_CHEETAH                      POOMA_NO
#define POOMA_MPI                          POOMA_NO
#define POOMA_THREADS                      POOMA_NO
#define POOMA_SCHEDULER_NAME               "stub scheduler"
#define POOMA_SMARTS_SCHEDULER_SERIALASYNC POOMA_NO
#define PETE_MAKE_EMPTY_CONSTRUCTORS       POOMA_NO
#define POOMA_PURIFY                       POOMA_NO
#define POOMA_INSURE                       POOMA_NO
#define POOMA_EXCEPTIONS                   POOMA_NO
#define POOMA_STRICT                       POOMA_NO
#define POOMA_ARCH_SPECIFIC_FUNCTIONS      POOMA_NO

#ifndef POOMA_DEFAULT_ENGINE_TYPE
#define POOMA_DEFAULT_ENGINE_TYPE          Brick
#endif

#ifndef POOMA_DEFAULT_DYNAMIC_ENGINE_TYPE
#define POOMA_DEFAULT_DYNAMIC_ENGINE_TYPE  Dynamic
#endif

#ifndef POOMA_DEFAULT_FLOAT_TYPE
#define POOMA_DEFAULT_FLOAT_TYPE           double
#endif

#ifndef POOMA_DEFAULT_ELEMENT_TYPE
#define POOMA_DEFAULT_ELEMENT_TYPE         double
#endif

#ifndef POOMA_DEFAULT_POSITION_TYPE
#define POOMA_DEFAULT_POSITION_TYPE        double
#endif

#ifndef POOMA_BOUNDS_CHECK
#define POOMA_BOUNDS_CHECK                 POOMA_NO
#endif

#ifndef POOMA_BOUNDS_CHECK_DEFAULT
#define POOMA_BOUNDS_CHECK_DEFAULT         POOMA_FALSE
#endif

#ifndef POOMA_DEFAULT_SMARTS_HARDINIT
#define POOMA_DEFAULT_SMARTS_HARDINIT      POOMA_TRUE
#endif

#ifndef POOMA_DEFAULT_SMARTS_HARDRUN
#define POOMA_DEFAULT_SMARTS_HARDRUN       POOMA_FALSE
#endif

#ifndef POOMA_DEFAULT_SMARTS_LOCKTHREADS
#define POOMA_DEFAULT_SMARTS_LOCKTHREADS   POOMA_FALSE
#endif

#ifndef POOMA_DEFAULT_BLOCKING_EXPRESSIONS
#define POOMA_DEFAULT_BLOCKING_EXPRESSIONS POOMA_FALSE
#endif

#define POOMA_NO_STRINGSTREAM              POOMA_NO
#define POOMA_MISSING_IOMANIPS             POOMA_NO
#define POOMA_NO_TEMPLATE_FRIENDS          POOMA_NO
#define POOMA_NO_RESTRICT                  POOMA_NO
#define POOMA_NO_OSTREAM_ITERATOR_1ARG     POOMA_NO
#define POOMA_NO_PLACEMENT_DELETE          POOMA_NO
#define POOMA_NO_DEPENDENT_TEMPLATE_ARGS   POOMA_NO
#define POOMA_NO_TEMPLATEFUNC_DEFAULTARGS  POOMA_NO
#define POOMA_NO_TEMPLATED_COMPLEX         POOMA_NO
#define POOMA_NO_STD_COMPLEX               POOMA_NO
#define POOMA_NO_IOS_HEADER                POOMA_NO
#define POOMA_NO_STD_IOSBASE               POOMA_NO
#define POOMA_NO_IOSBASE_FMTFLAGS          POOMA_NO
#define POOMA_NO_STD_MIN_MAX               POOMA_NO
#define POOMA_CLOCK_USES_GETTIMEOFDAY      POOMA_YES
#define POOMA_CLOCK_USES_CLOCK_GETTIME     POOMA_NO
#define POOMA_NONSTANDARD_ITERATOR         POOMA_NO
#define POOMA_HAS_LONG_LONG                POOMA_YES
#define POOMA_INT64                        long
#define POOMA_ATTRIBUTE_NORETURN           __attribute__((noreturn))

#endif

/*******************************************************
 * End of version information file PoomaConfiguration.h
 *******************************************************/
