#ifndef POOMA_DYNAMIC_ARRAY_DYNAMICARRAYOPERATORS_H
#define POOMA_DYNAMIC_ARRAY_DYNAMICARRAYOPERATORS_H

///////////////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE WAS GENERATED AUTOMATICALLY!
// YOU SHOULD MODIFY THE INPUT FILES INSTEAD OF CHANGING THIS FILE DIRECTLY!
//
// THE FOLLOWING INPUT FILES WERE USED TO MAKE THIS FILE:
//
// MakeOperators
// PoomaDynamicArray.in
//
///////////////////////////////////////////////////////////////////////////////


template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnArcCos,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
acos(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnArcCos,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnArcSin,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
asin(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnArcSin,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnArcTan,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
atan(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnArcTan,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnCeil,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
ceil(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnCeil,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnCos,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
cos(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnCos,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnHypCos,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
cosh(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnHypCos,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnExp,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
exp(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnExp,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnFabs,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
fabs(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnFabs,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnFloor,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
floor(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnFloor,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnLog,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
log(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnLog,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnLog10,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
log10(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnLog10,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnSin,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
sin(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnSin,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnHypSin,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
sinh(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnHypSin,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnSqrt,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
sqrt(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnSqrt,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnTan,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
tan(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnTan,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<FnHypTan,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
tanh(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<FnHypTan,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<OpUnaryMinus,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
operator-(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<OpUnaryMinus,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<OpUnaryPlus,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
operator+(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<OpUnaryPlus,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<OpBitwiseNot,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
operator~(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<OpBitwiseNot,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<OpIdentity,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
PETE_identity(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<OpIdentity,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class E1>
inline typename MakeReturn<UnaryNode<OpNot,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> >::Expression_t
operator!(const DynamicArray<T1,E1> & l)
{
  typedef UnaryNode<OpNot,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<UnaryNode<OpCast<T1>,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
peteCast(const T1&, const DynamicArray<T2,E2> & l)
{
  typedef UnaryNode<OpCast<T1>,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T2,E2> >::make(l)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator+(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator-(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator*(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator/(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator%(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator&(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator|(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator^(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
ldexp(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
pow(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
fmod(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
atan2(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<=(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>=(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator==(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator!=(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator&&(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator||(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<<(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>>(const DynamicArray<T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator+(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator-(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator*(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator/(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator%(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator&(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator|(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator^(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
ldexp(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
pow(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
fmod(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
atan2(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<=(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>=(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator==(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator!=(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator&&(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator||(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<<(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<int D1,class T1,class E1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>>(const Array<D1,T1,E1> & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<Array<D1,T1,E1> >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Array<D1,T1,E1> >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator+(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator-(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator*(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator/(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator%(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator&(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator|(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator^(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
ldexp(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
pow(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
fmod(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
atan2(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator<(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator<=(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator>(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator>=(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator==(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator!=(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator&&(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator||(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator<<(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,int D2,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> >::Expression_t
operator>>(const DynamicArray<T1,E1> & l,const Array<D2,T2,E2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<Array<D2,T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<Array<D2,T2,E2> >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator+(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator-(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator*(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator/(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator%(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator&(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator|(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator^(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
ldexp(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
pow(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
fmod(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
atan2(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<=(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>=(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator==(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator!=(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator&&(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator||(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<<(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class E1,class T2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>>(const DynamicArray<T1,E1> & l,const T2 & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator+(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator-(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator*(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator/(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator%(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator&(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator|(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator^(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
ldexp(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
pow(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
fmod(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
atan2(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<=(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>=(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator==(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator!=(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator&&(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator||(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}
#ifdef PETE_ALLOW_SCALAR_SHIFT

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator<<(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}

template<class T1,class T2,class E2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> >::Expression_t
operator>>(const T1 & l,const DynamicArray<T2,E2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<DynamicArray<T2,E2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<DynamicArray<T2,E2> >::make(r)));
}
#endif // PETE_ALLOW_SCALAR_SHIFT

template<class T1,class E1,class T2,class T3>
inline typename MakeReturn<TrinaryNode<FnWhere,
  typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t,
  typename CreateLeaf<T3 >::Leaf_t> >::Expression_t
where(const DynamicArray<T1,E1> & c,const T2 & t,const T3 & f)
{
  typedef TrinaryNode<FnWhere,
    typename CreateLeaf<DynamicArray<T1,E1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t,
    typename CreateLeaf<T3 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<DynamicArray<T1,E1> >::make(c),
    CreateLeaf<T2 >::make(t),
    CreateLeaf<T3 >::make(f)));
}

#endif // POOMA_DYNAMIC_ARRAY_DYNAMICARRAYOPERATORS_H

