# Generated by mm.pl: Wed Mar 11 22:10:45 MST 1998

# Set ODIR, PROJECT_INCLUDES, UNIQUE
include $(SHARED_ROOT)/include2.mk

# Object file list.
# This list is user-editable.
# Be sure that $(UNIQUE)_OBJS is set, even if set to empty.

$(UNIQUE)_OBJS := \
	$(ODIR)/UniformMapper.cmpl.o

LOCAL_OBJS += $($(UNIQUE)_OBJS)

# Set rules for the ODIR directory 
include $(SHARED_ROOT)/compilerules.mk

# ACL:rcsinfo
#  ----------------------------------------------------------------------
#  $RCSfile: objfile.mk,v $   $Author: richard $
#  $Revision: 1.5 $   $Date: 2004/11/01 18:17:01 $
#  ----------------------------------------------------------------------
# ACL:rcsinfo
