# Generated by mm.pl: Mon Mar  9 13:58:39 MST 1998

# Set ODIR, PROJECT_INCLUDES, UNIQUE
include $(SHARED_ROOT)/include2.mk

# Object file list.
# This list is user-editable.
# Be sure that $(UNIQUE)_OBJS is set, even if set to empty.

$(UNIQUE)_OBJS :=

LOCAL_OBJS += $($(UNIQUE)_OBJS)

# Set rules for the ODIR directory 
include $(SHARED_ROOT)/compilerules.mk

# ACL:rcsinfo
#  ----------------------------------------------------------------------
#  $RCSfile: objfile.mk,v $   $Author: richard $
#  $Revision: 1.6 $   $Date: 2004/11/01 18:17:07 $
#  ----------------------------------------------------------------------
# ACL:rcsinfo
