# Generated by mm.pl: Mon Mar  9 13:58:39 MST 1998

# Subdirectory list
# This file is user-editable. Add or remove blocks of three lines.


NEXTDIR := IterateSchedulers
include $(THISDIR)/$(NEXTDIR)/include.mk
THISDIR :=$(firstword $(DIR_LIST))

# ACL:rcsinfo
#  ----------------------------------------------------------------------
#  $RCSfile: subdir.mk,v $   $Author: richard $
#  $Revision: 1.3 $   $Date: 2004/11/01 18:17:07 $
#  ----------------------------------------------------------------------
# ACL:rcsinfo
